#LoginControl Config

#MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: LoginList
  username: root
  password: password

#First Login TP
OpJump: false
FirstPoint: false
world: world
x: 0
y: 0
z: 0
pitch: 0
yaw: 0

#Present Items
Present:
    - BED,1
    - BREAD,32
    - STONE_AXE,1
    - STONE_PICKAXE,1

#Ignore Report
Ignore-Names:
    - Kumaisu
Ignore-IP:
    - 127.0.0.0

#MotD Message
MotD1st: "%$dWelcome to Minecraft Server"
MotD2nd-Unknown: "%$3Let's play together"
MotD2nd-Player: "%$e%player%%$a, We are waiting for you"
# MotD1st: "%$fようこそ%$dMinecraft%$fサーバーへ"
# MotD2nd-Unknown: "%$3いっしょに遊びましょうよ"
# MotD2nd-Player: "%$e%player%%$aさん、まってますよ"
    
#Program Inner Messages
Message:
    LogFull: "%$aDisplay all logs"
    Reload: "%$aLoginList Config Reloaded."
    ArgsErr: "%$4Invalid argument specification, unknown argument specified"
    OptError: "%$4Incorrect log display specification"
#    LogFull: "%$aログをフル表示します"
#    Reload: "%$aコンフィグを再読込しました"
#    ArgsErr: "%$4引数指定の誤り：未知の引数が指定されました"
#    OptError: "%$4ログ表示指定に誤りがあります"

#Known servers
104.155.197.233: JapanMinecraftServer
213.239.204.169: Minecraft-Statistic
104.20.70.236: Minecraft-Server-List
104.20.237.39: MinecraftServers.org
72.52.216.181: MinecraftServers.net
104.25.139.100: MinecraftServers.biz
104.25.153.114: ServerPact.com
104.20.7.164: Minecraft-mp.com
104.31.90.225: mcserverstatus.com

#CDIR Host List
107.178.192.0/18: GoogleIncUS,MountainView)
54.216.0.0/15: AmazonCom(Ireland,Dublin)
