#LoginControl Config

#MySQL Settings
mysql:
  host: localhost
  port: 3306
  database: LoginList
  username: root
  password: password

#Ignore Report
Ignore-Names:
    - Kumaisu
Ignore-IP:
    - 127.0.0.0

#   Unknown IP Address Check Flag
CheckIP: false

#First Login TP
OpJump: false
FirstPoint: false
world: world
x: 0
y: 0
z: 0
pitch: 0
yaw: 0

#Present Items
Present:
    - BED,1
    - BREAD,32
    - STONE_AXE,1
    - STONE_PICKAXE,1

#MotD Message
MotD1st: "%$dWelcome to Minecraft Server"
MotD2nd-Unknown: "%$3Let's play together"
MotD2nd-Player: "%$e%player%%$a, We are waiting for you"
MotD2nd-Ping-Count: 100
MotD2nd-Ping: "You are going to confirm host survival %count times since %date"
# MotD1st: "%$fようこそ%$dMinecraft%$fサーバーへ"
# MotD2nd-Unknown: "%$3いっしょに遊びましょうよ"
# MotD2nd-Player: "%$e%player%%$aさん、まってますよ"
# MotD2nd-Ping: "貴方は %date から生存確認を %count 回実施しています"

#   Login時の案内表示用
#   /n で改行が可能、複数行の表示に対応
ANNOUNCE:
  Enabled: true
  Message: "%$e－－－  おしらせ  －－－/nDynmap URL[ %$4http://kumaisu.dip.jp:8123%$f ]/nHome Page
    [ %$4http://wikiwiki.jp/kumaisu/%$7 ]/nJMS Vote  [ %$4https://minecraft.jp/servers/kumaisu.dip.jp
    %$f]"

#   Login/Logout時のコメント表示用
#   複数行の表示には引対応
New_Join_Message:
  Enabled: true
  Message: "%$d%player% さん、スナック・クマイスサーバーへ、ようこそ"
Returning_Join_Message:
  Enabled: true
  Message: "%$b%player% %$dさん、おかえりなさい！ゆっくりしていってね！"
Quit_Message:
  Enabled: true
  Message: "%$b%player% %$dさんがログアウトしました"
Kick_Message:
  Enabled: true
  Message: "%$e%player% さんを$%4[%Reason%]$%eにより、サーバーからキックしました"
    
AutoMessages:
  Enabled: true
  UseBarAPI: true
  Interval: 20
  Prefix: "%$f[%$Server-INFO%$f]"
  NewLinePrefix: false
  Messages:
    global:
      interval: 5000
      use_permission: true
      permission: LoginCtl.AutoMessages.global
      list:
      - "%$7メインワールドでの建築などの作業は許可された場所のみになります"
      - "%$7難易度は%$4HARD%$7です、餓死に注意してね"
      - "%$7資源ﾜｰﾙﾄﾞでのTT作成は禁止しませんが、%$eﾜｰﾙﾄﾞﾘｾｯﾄ%$7時保護されません"
      - "%$7地下透視や能力向上系のﾂｰﾙ等の利用は禁止、%$4GlobalBAN%$7対象です"
      - "%$7ﾒｲﾝﾜｰﾙﾄﾞ以外は死亡時に%$eｱｲﾃﾑﾄﾞﾛｯﾌﾟ%$7するので注意してください"
      - "%$7ジョブに就いて、資金を稼ぎましょう/n%$4/jobs browse %$7で職種が確認できます"
      - "%$7鯖の情報用に %$eDiscord %$7を運用しています/n[ %$bhttps://discord.gg/AgX3UxR%$7 ]"
      - "%$7ｴﾚﾍﾞｰﾀは看板を右ｸﾘｯｸで行きたい階を選べるよ"
      - "%$3send&7や%$3tell%$7コマンドは相手が不在でもメールとして届くよ"
      - "%$7ルールやコマンドなどは%$ewiki%$7で確認してください/n[ %$bhttp://wikiwiki.jp/kumaisu/%$7 ]"
      - "%$7鯖発展のため、是非投票をお願いします/n[ %$bhttps://minecraft.jp/servers/kumaisu.dip.jp%$7 ]"
      - "%$e注意:%$f大規模な%$4窃盗行為%$fがありました、/n無料アパートにお住まいの方は、各自部屋を確認してください"
    vip:
      interval: 8000
      use_permission: true
      permission: LoginCtl.AutoMessages.vip
      list:
      - "%$f運営メンバー募集、詳しくは%$eKumaisu%$fまで問合せください"
      - "%$fプラグイン開発協力者募集中です、詳細は個別対応になります"
      - "%$3send&7や%$3tell%$fコマンドは相手が不在でもメールとして届くよ"
      - "%$f鯖の情報用に %$eDiscord %$fを運用しています/n[ %$bhttps://discord.gg/AgX3UxR%$f ]"
      - "%$fItemShopのﾁｪｽﾄは破壊可能、ｶﾞﾗｽ部分に看板も設置可能です"
      - "%$fルールやコマンドなどは%$ewiki%$fで確認してください/n[ %$bhttp://wikiwiki.jp/kumaisu/%$f ]"
      - "%$f鯖発展のため、是非投票をお願いします/n[ %$bhttps://minecraft.jp/servers/kumaisu.dip.jp%$f ]"

#   死亡時のメッセージ類
Death_Message:
  Enabled: true
  Messages:
    Player: "%$9%world% %$cで%$player% %$cさんを%$9%killer% %$cさんが%$9%weapon% %$cで殺しました"
    DEFAULT: "%$c%player% %$7was killed by a %$c%mob%"
    ZOMBIE: "%$b%player%%$f は%$c %mob% %$7に殺された"
    CREEPER: "%$b%player% %$7は%$c %mob% %$7のリフォームの巻き添えになってしまった"
    HUSK: "%$b%player%%$f は%$c %mob% %$7に殺された"
    SHULKER: "%$c%player% %$7was shot by a %$c%mob%"
    PIG_ZOMBIE: "%$b%player%%$f は%$c %mob% %$7に殺された"
    SKELETON: "%$b%player%%$f は%$c %mob% %$7に殺された"
    GHAST: "%$b%player%%$f は%$c %mob% %$7に殺された"
    MAGMA_CUBE: "%$b%player%%$f は%$c %mob% %$7に殺された"
    SLIME: "%$b%player%%$f は%$c %mob% %$7に殺された"
    WOLF: "%$c%player% %$7はかわいい%$c%mob% %$7に復讐された"
    SPIDER: "%$b%player%%$f は%$c %mob% %$7に殺された"
    CAVE_SPIDER: "%$b%player%%$f は%$c %mob% %$7に殺された"
    GIANT: "%$c%player% %$7はとっても大きい%$c%mob% %$7に殺された!"
    BLAZE: "%$b%player%%$f は%$c %mob% %$7に殺された"
    SILVERFISH: "%$b%player%%$f は%$c %mob% %$7に殺された"
    ENDERMAN: "%$b%player%%$f は%$c %mob% %$7に殺された"
    ENDER_DRAGON: "%$b%player%%$f は%$c %mob% %$7に殺された"
    WITHER: "%$b%player%%$f は%$c %mob% %$7に殺された"
    WITHER_BOSS: "%$b%player%%$f は%$c %mob% %$7に殺された"
    IRON_GOLEM: "%$b%player%%$f は%$c %mob% %$7に殺された"
    DROWNING: "%$c%player% %$7は夢中になりすぎて溺れてしまった・・・"
    FALL: "%$c%player% %$7はピーターパンにはなれなかった・・・"
    FIRE: "%$c%player% %$7燃え尽きてしまった"
    SUFFOCATION: "%$c%player% %$7suffocated"
    VOID: "%$c%player% %$7Fell into the Void"
    STARVATION: "%$c%player% %$7Starved To Death"
    SUICIDE: "%$c%player% %$7Decided To End It All"
    MAGIC: "%$c%player% %$7was killed by magic"
    POISON: "%$c%player% %$7was poisoned to death!"
    LIGHTENING: "%$c%player% %$7was struck by lightening!"
    LAVA: "%$c%player% %$7は、マグマダイブを試みた"
    FIRE_TICK: "%$c%player% %$7died from the burns of fire"
    ENDER_PEARL: "%$c%player% %$7died from throwing an ender pearl"
    CONTACT: "%$c%player% %$7was pricked by a %$cCactus"
    BLOCK_EXPLOSION: "%$c%player% %$7blew up"
    UnknownReason: "%player% Just Died... (Cause: %cause%)"

#Program Inner Messages
Message:
    LogFull: "%$aDisplay all logs"
    Reload: "%$aLoginList Config Reloaded."
    ArgsErr: "%$4Invalid argument specification, unknown argument specified"
    OptError: "%$4Incorrect log display specification"
#    LogFull: "%$aログをフル表示します"
#    Reload: "%$aコンフィグを再読込しました"
#    ArgsErr: "%$4引数指定の誤り：未知の引数が指定されました"
#    OptError: "%$4ログ表示指定に誤りがあります"

#Known servers
104.155.197.233: JapanMinecraftServer
213.239.204.169: Minecraft-Statistic
104.20.70.236: Minecraft-Server-List
104.20.237.39: MinecraftServers.org
72.52.216.181: MinecraftServers.net
104.25.139.100: MinecraftServers.biz
104.25.153.114: ServerPact.com
104.20.7.164: Minecraft-mp.com
104.31.90.225: mcserverstatus.com

#CDIR Host List
107.178.192.0/18: GoogleIncUS,MountainView)
54.216.0.0/15: AmazonCom(Ireland,Dublin)
