name: LoginControl
version: 0.0.1
main: com.mycompany.logincontrol.LoginControl
description: login history plugins
author: Kumaisu
database: true
commands:
    loginlist:
        description: Login History Print
        aliases: ll
        permission: LoginCtl.loginlist
        permission-message: You do not have permission.
        usage: /<command> [full] [d:yymmdd] [u:player name]
    loginctl:
        description: LoginControl Admin Commands
        permission: LoginCtl.admin
        permission-message: You do not have permission.
        usage: |
            /<command> reload
            /<command> status
            /<command> info:[IP]
            /<command> chg:[IP]:[HostName]
            /<command> pingtop
permissions:
    LoginCtl.silent:
        description: Silent Login non Messages
        default: false
