name: LoginControl
version: 0.0.1
main: com.mycompany.logincontrol.LoginControl
description: login history plugins
author: Kumaisu
database: true
commands:
    flight:
        description: Fly Switch
        permission: LoginCtl.fly
        permission-message: You do not have permission.
        usage: /<command> [on/off]
    ping:
        description: Inet Ping Command
        default: op
        usage: /<command> IPAddress or HostName
    loginlist:
        description: Login History Print
        aliases: ll
        permission: LoginCtl.loginlist
        permission-message: You do not have permission.
        usage: /<command> [full] [d:yymmdd] [u:player name]
    loginctl:
        description: LoginControl Admin Commands
        permission: LoginCtl.admin
        permission-message: You do not have permission.
        usage: |
            /<command> reload
            /<command> status
            /<command> info IPAddress
            /<command> chg IPAddress HostName
            /<command> add IPAddress [HostName]
            /<command> del IPAddress
            /<command> pingtop
            /<command> checkIP
permissions:
    LoginCtl.silentjoin:
        description: Silent Login non Message
        default: false
    LoginCtl.silentquit:
        description: Silent Quit non Message
        default: false

